redis:
  auth:
    password: "redis-prod-pass"
  
  master:
    persistence:
      size: 10Gi
    
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
      requests:
        memory: 512Mi
        cpu: 500m
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
