apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-ingestion-service
  namespace: default
  labels:
    app: iot-ingestion-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-ingestion-service
  template:
    metadata:
      labels:
        app: iot-ingestion-service
    spec:
      containers:
      - name: iot-data-service
        image: ankittripathi100/iot-ingestion-service:latest  # Replace with updated Docker registry, if any.
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        