postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "postgres"
        username: "iotuser"
        password: "iotpassword"
        database: "iotdb"
  
  primary:
    persistence:
      enabled: true
      size: 10Gi
    
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
      requests:
        memory: 256Mi
        cpu: 250m

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false  # Set to true if using Prometheus Operator
