version: '3.8'

services:
  prediction-service:
    build:
      context: .
      dockerfile: prediction-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - backend-network

  data-service:
    build:
      context: .
      dockerfile: data-service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - backend-network

  ingestion-service:
    build:
      context: .
      dockerfile: ingestion-service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
