postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "postgres-staging"
        username: "iotuser"
        password: "iotpass-staging"
        database: "iotdb"
  
  primary:
    persistence:
      size: 10Gi
    
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
      requests:
        memory: 512Mi
        cpu: 500m
  
  metrics:
    enabled: true
