postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "postgres-dev"
        username: "iotuser"
        password: "iotpass-dev"
        database: "iotdb"
  
  primary:
    persistence:
      size: 5Gi
    
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
  
  metrics:
    enabled: false
