replicaCount: 1

image:
  repository: ankittripathi100/iot-dashboard
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: atripathi.tech
      paths:
        - path: /
          pathType: Prefix

env:
  - name: REACT_APP_API_URL
    value: "http://backend-service:8000"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
